[package]
authors = ["lettenj61 <lettenj61@users.noreply.github.com>"]
description = "Macros for hasty, sketchy, funny Rust programming."
license = "Apache/MIT"
name = "rucky-macros"
version = "0.1.0"

[features]
default = []
test_attr = []

[dependencies]

[dev-dependencies]
rand = "0.3"
rustc-serialize = "0.3"
toml = "0.2"
